In [1]:
import pandas as pd

df = pd.read_parquet("../data/bronze/insee/annee=2021/insee_2021.parquet")
print(df.shape)
df.head()

(34929, 572)

,CODGEO,NBMEN21,NBPERS21,NBUC21,PMIMP21,Q121,Q221,Q321,Q3_Q1,D121,...,OPR5D921,OPR5RD,OPR5S80S2021,OPR5GI21,OPR5PACT21,OPR5PTSA21,OPR5PCHO21,OPR5PBEN21,OPR5PPEN21,OPR5PAUT21
0,01001,346,895,"590,8",s,s,26410,s,s,s,...,s,s,s,s,s,s,s,s,s,s
1,01002,115,266,"181,0",s,s,24950,s,s,s,...,s,s,s,s,s,s,s,s,s,s
2,01004,6861,15103,"10406,5","50,0",13180,20940,29260,16080,7070,...,s,s,s,s,s,s,s,s,s,s
3,01005,801,2030,"1331,2","61,0",18900,24800,32660,13760,13450,...,s,s,s,s,s,s,s,s,s,s
4,01006,51,107,"76,6",s,s,24080,s,s,s,...,s,s,s,s,s,s,s,s,s,s

In [2]:
df.columns.tolist()

['CODGEO',
 'NBMEN21',
 'NBPERS21',
 'NBUC21',
 'PMIMP21',
 'Q121',
 'Q221',
 'Q321',
 'Q3_Q1',
 'D121',
 'D221',
 'D321',
 'D421',
 'D621',
 'D721',
 'D821',
 'D921',
 'RD',
 'S80S2021',
 'GI21',
 'PACT21',
 'PTSA21',
 'PCHO21',
 'PBEN21',
 'PPEN21',
 'PAUT21',
 'AGE1Q121',
 'AGE1Q221',
 'AGE1Q321',
 'AGE1Q3_Q1',
 'AGE1D121',
 'AGE1D221',
 'AGE1D321',
 'AGE1D421',
 'AGE1D621',
 'AGE1D721',
 'AGE1D821',
 'AGE1D921',
 'AGE1RD',
 'AGE1S80S2021',
 'AGE1GI21',
 'AGE1PACT21',
 'AGE1PTSA21',
 'AGE1PCHO21',
 'AGE1PBEN21',
 'AGE1PPEN21',
 'AGE1PAUT21',
 'AGE2Q121',
 'AGE2Q221',
 'AGE2Q321',
 'AGE2Q3_Q1',
 'AGE2D121',
 'AGE2D221',
 'AGE2D321',
 'AGE2D421',
 'AGE2D621',
 'AGE2D721',
 'AGE2D821',
 'AGE2D921',
 'AGE2RD',
 'AGE2S80S2021',
 'AGE2GI21',
 'AGE2PACT21',
 'AGE2PTSA21',
 'AGE2PCHO21',
 'AGE2PBEN21',
 'AGE2PPEN21',
 'AGE2PAUT21',
 'AGE3Q121',
 'AGE3Q221',
 'AGE3Q321',
 'AGE3Q3_Q1',
 'AGE3D121',
 'AGE3D221',
 'AGE3D321',
 'AGE3D421',
 'AGE3D621',
 'AGE3D721',
 'AGE3D821',
 'AGE3D921',
 'AGE3RD',
 'AGE3S80S2021',
 'AGE3GI21',
 'AGE3PACT21',
 'AGE3PTSA21',
 'AGE3PCHO21',
 'AGE3PBEN21',
 'AGE3PPEN21',
 'AGE3PAUT21',
 'AGE4Q121',
 'AGE4Q221',
 'AGE4Q321',
 'AGE4Q3_Q1',
 'AGE4D121',
 'AGE4D221',
 'AGE4D321',
 'AGE4D421',
 'AGE4D621',
 'AGE4D721',
 'AGE4D821',
 'AGE4D921',
 'AGE4RD',
 'AGE4S80S2021',
 'AGE4GI21',
 'AGE4PACT21',
 'AGE4PTSA21',
 'AGE4PCHO21',
 'AGE4PBEN21',
 'AGE4PPEN21',
 'AGE4PAUT21',
 'AGE5Q121',
 'AGE5Q221',
 'AGE5Q321',
 'AGE5Q3_Q1',
 'AGE5D121',
 'AGE5D221',
 'AGE5D321',
 'AGE5D421',
 'AGE5D621',
 'AGE5D721',
 'AGE5D821',
 'AGE5D921',
 'AGE5RD',
 'AGE5S80S2021',
 'AGE5GI21',
 'AGE5PACT21',
 'AGE5PTSA21',
 'AGE5PCHO21',
 'AGE5PBEN21',
 'AGE5PPEN21',
 'AGE5PAUT21',
 'AGE6Q121',
 'AGE6Q221',
 'AGE6Q321',
 'AGE6Q3_Q1',
 'AGE6D121',
 'AGE6D221',
 'AGE6D321',
 'AGE6D421',
 'AGE6D621',
 'AGE6D721',
 'AGE6D821',
 'AGE6D921',
 'AGE6RD',
 'AGE6S80S2021',
 'AGE6GI21',
 'AGE6PACT21',
 'AGE6PTSA21',
 'AGE6PCHO21',
 'AGE6PBEN21',
 'AGE6PPEN21',
 'AGE6PAUT21',
 'TME1Q121',
 'TME1Q221',
 'TME1Q321',
 'TME1Q3_Q1',
 'TME1D121',
 'TME1D221',
 'TME1D321',
 'TME1D421',
 'TME1D621',
 'TME1D721',
 'TME1D821',
 'TME1D921',
 'TME1RD',
 'TME1S80S2021',
 'TME1GI21',
 'TME1PACT21',
 'TME1PTSA21',
 'TME1PCHO21',
 'TME1PBEN21',
 'TME1PPEN21',
 'TME1PAUT21',
 'TME2Q121',
 'TME2Q221',
 'TME2Q321',
 'TME2Q3_Q1',
 'TME2D121',
 'TME2D221',
 'TME2D321',
 'TME2D421',
 'TME2D621',
 'TME2D721',
 'TME2D821',
 'TME2D921',
 'TME2RD',
 'TME2S80S2021',
 'TME2GI21',
 'TME2PACT21',
 'TME2PTSA21',
 'TME2PCHO21',
 'TME2PBEN21',
 'TME2PPEN21',
 'TME2PAUT21',
 'TME3Q121',
 'TME3Q221',
 'TME3Q321',
 'TME3Q3_Q1',
 'TME3D121',
 'TME3D221',
 'TME3D321',
 'TME3D421',
 'TME3D621',
 'TME3D721',
 'TME3D821',
 'TME3D921',
 'TME3RD',
 'TME3S80S2021',
 'TME3GI21',
 'TME3PACT21',
 'TME3PTSA21',
 'TME3PCHO21',
 'TME3PBEN21',
 'TME3PPEN21',
 'TME3PAUT21',
 'TME4Q121',
 'TME4Q221',
 'TME4Q321',
 'TME4Q3_Q1',
 'TME4D121',
 'TME4D221',
 'TME4D321',
 'TME4D421',
 'TME4D621',
 'TME4D721',
 'TME4D821',
 'TME4D921',
 'TME4RD',
 'TME4S80S2021',
 'TME4GI21',
 'TME4PACT21',
 'TME4PTSA21',
 'TME4PCHO21',
 'TME4PBEN21',
 'TME4PPEN21',
 'TME4PAUT21',
 'TME5Q121',
 'TME5Q221',
 'TME5Q321',
 'TME5Q3_Q1',
 'TME5D121',
 'TME5D221',
 'TME5D321',
 'TME5D421',
 'TME5D621',
 'TME5D721',
 'TME5D821',
 'TME5D921',
 'TME5RD',
 'TME5S80S2021',
 'TME5GI21',
 'TME5PACT21',
 'TME5PTSA21',
 'TME5PCHO21',
 'TME5PBEN21',
 'TME5PPEN21',
 'TME5PAUT21',
 'TOL1Q121',
 'TOL1Q221',
 'TOL1Q321',
 'TOL1Q3_Q1',
 'TOL1D121',
 'TOL1D221',
 'TOL1D321',
 'TOL1D421',
 'TOL1D621',
 'TOL1D721',
 'TOL1D821',
 'TOL1D921',
 'TOL1RD',
 'TOL1S80S2021',
 'TOL1GI21',
 'TOL1PACT21',
 'TOL1PTSA21',
 'TOL1PCHO21',
 'TOL1PBEN21',
 'TOL1PPEN21',
 'TOL1PAUT21',
 'TOL2Q121',
 'TOL2Q221',
 'TOL2Q321',
 'TOL2Q3_Q1',
 'TOL2D121',
 'TOL2D221',
 'TOL2D321',
 'TOL2D421',
 'TOL2D621',
 'TOL2D721',
 'TOL2D821',
 'TOL2D921',
 'TOL2RD',
 'TOL2S80S2021',
 'TOL2GI21',
 'TOL2PACT21',
 'TOL2PTSA21',
 'TOL2PCHO21',
 'TOL2PBEN21',
 'TOL2PPEN21',
 'TOL2PAUT21',
 'TLD2Q121',
 'TLD2Q221',
 'TLD2Q321',
 'TLD2Q3_Q1',
 'TLD2D121',
 'TLD2D221',
 'TLD2D321',
 'TLD2D421',
 'TLD2D621',
 'TLD2D721',
 'TLD2D821',
 'TLD2D921',
 'TLD2RD',
 'TLD2S80S2021',
 'TLD2GI21',
 'TLD2PACT21',
 'TLD2PTSA21',
 'TLD2PCHO21',
 'TLD2PBEN21',
 'TLD2PPEN21',
 'TLD2PAUT21',
 'TLD3Q121',
 'TLD3Q221',
 'TLD3Q321',
 'TLD3Q3_Q1',
 'TLD3D121',
 'TLD3D221',
 'TLD3D321',
 'TLD3D421',
 'TLD3D621',
 'TLD3D721',
 'TLD3D821',
 'TLD3D921',
 'TLD3RD',
 'TLD3S80S2021',
 'TLD3GI21',
 'TLD3PACT21',
 'TLD3PTSA21',
 'TLD3PCHO21',
 'TLD3PBEN21',
 'TLD3PPEN21',
 'TLD3PAUT21',
 'TYM1Q121',
 'TYM1Q221',
 'TYM1Q321',
 'TYM1Q3_Q1',
 'TYM1D121',
 'TYM1D221',
 'TYM1D321',
 'TYM1D421',
 'TYM1D621',
 'TYM1D721',
 'TYM1D821',
 'TYM1D921',
 'TYM1RD',
 'TYM1S80S2021',
 'TYM1GI21',
 'TYM1PACT21',
 'TYM1PTSA21',
 'TYM1PCHO21',
 'TYM1PBEN21',
 'TYM1PPEN21',
 'TYM1PAUT21',
 'TYM2Q121',
 'TYM2Q221',
 'TYM2Q321',
 'TYM2Q3_Q1',
 'TYM2D121',
 'TYM2D221',
 'TYM2D321',
 'TYM2D421',
 'TYM2D621',
 'TYM2D721',
 'TYM2D821',
 'TYM2D921',
 'TYM2RD',
 'TYM2S80S2021',
 'TYM2GI21',
 'TYM2PACT21',
 'TYM2PTSA21',
 'TYM2PCHO21',
 'TYM2PBEN21',
 'TYM2PPEN21',
 'TYM2PAUT21',
 'TYM3Q121',
 'TYM3Q221',
 'TYM3Q321',
 'TYM3Q3_Q1',
 'TYM3D121',
 'TYM3D221',
 'TYM3D321',
 'TYM3D421',
 'TYM3D621',
 'TYM3D721',
 'TYM3D821',
 'TYM3D921',
 'TYM3RD',
 'TYM3S80S2021',
 'TYM3GI21',
 'TYM3PACT21',
 'TYM3PTSA21',
 'TYM3PCHO21',
 'TYM3PBEN21',
 'TYM3PPEN21',
 'TYM3PAUT21',
 'TYM4Q121',
 'TYM4Q221',
 'TYM4Q321',
 'TYM4Q3_Q1',
 'TYM4D121',
 'TYM4D221',
 'TYM4D321',
 'TYM4D421',
 'TYM4D621',
 'TYM4D721',
 'TYM4D821',
 'TYM4D921',
 'TYM4RD',
 'TYM4S80S2021',
 'TYM4GI21',
 'TYM4PACT21',
 'TYM4PTSA21',
 'TYM4PCHO21',
 'TYM4PBEN21',
 'TYM4PPEN21',
 'TYM4PAUT21',
 'TYM5Q121',
 'TYM5Q221',
 'TYM5Q321',
 'TYM5Q3_Q1',
 'TYM5D121',
 'TYM5D221',
 'TYM5D321',
 'TYM5D421',
 'TYM5D621',
 'TYM5D721',
 'TYM5D821',
 'TYM5D921',
 'TYM5RD',
 'TYM5S80S2021',
 'TYM5GI21',
 'TYM5PACT21',
 'TYM5PTSA21',
 'TYM5PCHO21',
 'TYM5PBEN21',
 'TYM5PPEN21',
 'TYM5PAUT21',
 'TYM6Q121',
 'TYM6Q221',
 'TYM6Q321',
 'TYM6Q3_Q1',
 'TYM6D121',
 'TYM6D221',
 'TYM6D321',
 'TYM6D421',
 'TYM6D621',
 'TYM6D721',
 'TYM6D821',
 'TYM6D921',
 'TYM6RD',
 'TYM6S80S2021',
 'TYM6GI21',
 'TYM6PACT21',
 'TYM6PTSA21',
 'TYM6PCHO21',
 'TYM6PBEN21',
 'TYM6PPEN21',
 'TYM6PAUT21',
 'OPR1Q121',
 'OPR1Q221',
 'OPR1Q321',
 'OPR1Q3_Q1',
 'OPR1D121',
 'OPR1D221',
 'OPR1D321',
 'OPR1D421',
 'OPR1D621',
 'OPR1D721',
 'OPR1D821',
 'OPR1D921',
 'OPR1RD',
 'OPR1S80S2021',
 'OPR1GI21',
 'OPR1PACT21',
 'OPR1PTSA21',
 'OPR1PCHO21',
 'OPR1PBEN21',
 'OPR1PPEN21',
 'OPR1PAUT21',
 'OPR2Q121',
 'OPR2Q221',
 'OPR2Q321',
 'OPR2Q3_Q1',
 'OPR2D121',
 'OPR2D221',
 'OPR2D321',
 'OPR2D421',
 'OPR2D621',
 'OPR2D721',
 'OPR2D821',
 'OPR2D921',
 'OPR2RD',
 'OPR2S80S2021',
 'OPR2GI21',
 'OPR2PACT21',
 'OPR2PTSA21',
 'OPR2PCHO21',
 'OPR2PBEN21',
 'OPR2PPEN21',
 'OPR2PAUT21',
 'OPR3Q121',
 'OPR3Q221',
 'OPR3Q321',
 'OPR3Q3_Q1',
 'OPR3D121',
 'OPR3D221',
 'OPR3D321',
 'OPR3D421',
 'OPR3D621',
 'OPR3D721',
 'OPR3D821',
 'OPR3D921',
 'OPR3RD',
 'OPR3S80S2021',
 'OPR3GI21',
 'OPR3PACT21',
 'OPR3PTSA21',
 'OPR3PCHO21',
 'OPR3PBEN21',
 'OPR3PPEN21',
 'OPR3PAUT21',
 'OPR4Q121',
 'OPR4Q221',
 'OPR4Q321',
 'OPR4Q3_Q1',
 'OPR4D121',
 'OPR4D221',
 'OPR4D321',
 'OPR4D421',
 'OPR4D621',
 'OPR4D721',
 'OPR4D821',
 'OPR4D921',
 'OPR4RD',
 'OPR4S80S2021',
 'OPR4GI21',
 'OPR4PACT21',
 'OPR4PTSA21',
 'OPR4PCHO21',
 'OPR4PBEN21',
 'OPR4PPEN21',
 'OPR4PAUT21',
 'OPR5Q121',
 'OPR5Q221',
 'OPR5Q321',
 'OPR5Q3_Q1',
 'OPR5D121',
 'OPR5D221',
 'OPR5D321',
 'OPR5D421',
 'OPR5D621',
 'OPR5D721',
 'OPR5D821',
 'OPR5D921',
 'OPR5RD',
 'OPR5S80S2021',
 'OPR5GI21',
 'OPR5PACT21',
 'OPR5PTSA21',
 'OPR5PCHO21',
 'OPR5PBEN21',
 'OPR5PPEN21',
 'OPR5PAUT21']

In [6]:
print(df.dtypes)

CODGEO        str
NBMEN21       str
NBPERS21      str
NBUC21        str
PMIMP21       str
             ...
OPR5PTSA21    str
OPR5PCHO21    str
OPR5PBEN21    str
OPR5PPEN21    str
OPR5PAUT21    str
Length: 572, dtype: object

In [4]:
df.isnull().sum()

CODGEO        0
NBMEN21       0
NBPERS21      0
NBUC21        0
PMIMP21       0
             ..
OPR5PTSA21    0
OPR5PCHO21    0
OPR5PBEN21    0
OPR5PPEN21    0
OPR5PAUT21    0
Length: 572, dtype: int64

In [5]:
df.describe()

,CODGEO,NBMEN21,NBPERS21,NBUC21,PMIMP21,Q121,Q221,Q321,Q3_Q1,D121,...,OPR5D921,OPR5RD,OPR5S80S2021,OPR5GI21,OPR5PACT21,OPR5PTSA21,OPR5PCHO21,OPR5PBEN21,OPR5PPEN21,OPR5PAUT21
count,34929,34929,34929,34929,34929,34929,34929,34929,34929,34929,...,34929,34929,34929,34929,34929,34929,34929,34929,34929,34929
unique,34929,3818,5746,13791,70,1571,2395,2020,1419,1529,...,848,554,689,377,188,155,32,58,169,231
top,01001,s,s,s,s,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
freq,1,3594,3594,3594,29570,29570,3594,29570,29570,29570,...,34057,34057,34057,34057,34061,34327,34327,34327,34061,34061

In [7]:
# Regarder les valeurs de Q221 (revenu médian)
print(df["Q221"].value_counts().head(20))

# Combien de communes ont le secret statistique ?
print(f"\nCommunes avec secret statistique sur Q221 : {(df['Q221'] == 's').sum()}")
print(f"Communes avec revenu médian disponible : {(df['Q221'] != 's').sum()}")

Q221
s        3594
21140      65
21720      60
21800      57
22210      57
22700      57
20510      57
21590      56
22670      56
21670      56
21530      55
21760      55
22130      55
21130      54
22170      54
20490      53
21120      52
20900      52
22010      52
22000      52
Name: count, dtype: int64

Communes avec secret statistique sur Q221 : 3594
Communes avec revenu médian disponible : 31335

In [8]:
# Remplacer "s" par NaN et convertir en float
df["revenu_median"] = pd.to_numeric(
    df["Q221"].replace("s", None),
    errors="coerce"
)

# Vérification
print(df["revenu_median"].describe())
print(f"\nNulls : {df['revenu_median'].isna().sum()}")

count    31326.000000
mean     23094.224925
std       3862.471774
min       8760.000000
25%      20700.000000
50%      22540.000000
75%      24820.000000
max      60920.000000
Name: revenu_median, dtype: float64

Nulls : 3603

In [9]:
cols_utiles = [
    "CODGEO",        # code INSEE commune
    "Q221",          # revenu médian brut
    "D121",          # 1er décile
    "D921",          # 9ème décile
]

df_cols_utiles = df[cols_utiles].copy()

# Convertir toutes les colonnes numériques
for col in ["Q221", "D121", "D921"]:
    df_cols_utiles[col] = pd.to_numeric(
        df_cols_utiles[col].replace("s", None),
        errors="coerce"
    )

# Renommer pour plus de clarté
df_cols_utiles = df_cols_utiles.rename(columns={
    "CODGEO": "code_insee",
    "Q221": "revenu_median",
    "D121": "revenu_d1",
    "D921": "revenu_d9"
})

print(df_cols_utiles.dtypes)
print(df_cols_utiles.describe())

code_insee           str
revenu_median    float64
revenu_d1        float64
revenu_d9        float64
dtype: object
       revenu_median     revenu_d1      revenu_d9
count   31326.000000   5350.000000    5350.000000
mean    23094.224925  10278.132710   43850.456075
std      3862.471774   3778.555832   11979.789815
min      8760.000000      0.000000   25260.000000
25%     20700.000000   7760.000000   36740.000000
50%     22540.000000  10670.000000   40750.000000
75%     24820.000000  13070.000000   47330.000000
max     60920.000000  22520.000000  199290.000000

In [15]:
# Vérification cohérence entre années
annees = [2017, 2018, 2019, 2020, 2021]

for annee in annees:
    df_tmp = pd.read_parquet(f"../data/bronze/insee/annee={annee}/insee_{annee}.parquet")
    a_q2 = "Q2" + str(annee)[-2:] in df_tmp.columns
    print(f"{annee} → {df_tmp.shape} | colonne revenu médian Q2{str(annee)[-2:]} : {a_q2}")

2017 → (31745, 27) | colonne revenu médian Q217 : True
2018 → (31327, 572) | colonne revenu médian Q218 : True
2019 → (31364, 572) | colonne revenu médian Q219 : True
2020 → (34939, 572) | colonne revenu médian Q220 : True
2021 → (34929, 572) | colonne revenu médian Q221 : True